# -*- coding: utf-8 -*-
"""Avance2_Tema[1]_Bellini_Herrera_Ramirez_Tafalla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nd9n6lcv9xzBcTpasGLyKC7L16_0CJbI

#1. Instalación de librerias
Adjuntamos el archivo csv en la entrega. Por favor, para poder correr el codigo correctamente, cargar el archivo csv en Google Drive y pegar la ruta del archivo a la variable llamada RUTA_ARCHIVO.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score
from sklearn.pipeline import make_pipeline
import warnings
warnings.filterwarnings('ignore')  # Suprimir advertencias menores

# Configuración general de gráficas
plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['font.size'] = 12
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.4


# Cargar el dataset usando Google Drive

# Montar Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Ruta del archivo CSV
# Por favor, corrige esta ruta al lugar donde se encuentra tu archivo CSV.
# Basado en los archivos disponibles, el archivo está en la raíz de /content/
RUTA_ARCHIVO = '/content/Tipo cambio de compra y de venta del dólar de los Estados Unidos de América (1).csv'

# --- VERIFICACIÓN DE RUTA --- #
import os
carpeta_csv = os.path.dirname(RUTA_ARCHIVO)
print(f"\nVerificando contenido de la carpeta: {carpeta_csv}")
if os.path.exists(carpeta_csv):
    print("Archivos encontrados:")
    for item in os.listdir(carpeta_csv):
        print(f"  - {item}")
else:
    print(f"  La carpeta '{carpeta_csv}' no existe. Por favor, verifica la ruta.")
print("------------------------------")
# --- FIN VERIFICACIÓN --- #


# --- 1.3 Función de carga robusta ---
def cargar_datos(ruta):
    """
    Carga el CSV del BCCR de forma robusta, manejando:
      - Diferentes encodings (utf-8, latin-1, cp1252)
      - Separadores alternativos (; o ,)
      - Filas de encabezado adicionales al inicio
      - Nombres de columnas con espacios o caracteres especiales

    Parámetros:
        ruta (str): Ruta completa al archivo CSV

    Retorna:
        DataFrame de pandas con los datos crudos
    """
    encodings = ['utf-8', 'latin-1', 'cp1252', 'iso-8859-1']
    separadores = [',', ';', '\t']

    for encoding in encodings:
        for sep in separadores:
            try:
                # Intentar leer saltando hasta 5 filas de encabezado
                for skip in range(6):
                    try:
                        df = pd.read_csv(
                            ruta,
                            encoding=encoding,
                            sep=sep,
                            skiprows=skip,
                            thousands=',',      # manejar números con coma de miles
                            on_bad_lines='skip'
                        )
                        # Verificar que el DataFrame tiene al menos 3 columnas y filas
                        if df.shape[1] >= 3 and df.shape[0] > 10:
                            print(f" Archivo cargado con encoding='{encoding}', "
                                  f"sep='{sep}', filas_omitidas={skip}")
                            return df
                    except Exception:
                        continue
            except Exception:
                continue

    raise ValueError("No se pudo cargar el archivo. Verifica la ruta y el formato.")


# Cargar el archivo
df_crudo = cargar_datos(RUTA_ARCHIVO)

# Vista previa del archivo crudo
print("\n Vista previa del archivo crudo:")
print(df_crudo.head(10))
print(f"\nDimensiones originales: {df_crudo.shape[0]} filas × {df_crudo.shape[1]} columnas")
print(f"Columnas detectadas: {list(df_crudo.columns)}")

# --- Inspección manual del archivo CSV ---
print(f"\nIntentando leer las primeras líneas de: {RUTA_ARCHIVO}")

try:
    with open(RUTA_ARCHIVO, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            print(f"Línea {i+1}: {line.strip()}")
            if i >= 9: # Leer las primeras 10 líneas
                break
except UnicodeDecodeError:
    print("\n  Error de codificación al intentar leer con UTF-8. Probando con latin-1...")
    try:
        with open(RUTA_ARCHIVO, 'r', encoding='latin-1') as f:
            for i, line in enumerate(f):
                print(f"Línea {i+1}: {line.strip()}")
                if i >= 9:
                    break
    except Exception as e:
        print(f"\n  No se pudo leer el archivo con latin-1. Error: {e}")
except FileNotFoundError:
    print("\n  Error: El archivo no fue encontrado en la ruta especificada.")
except Exception as e:
    print(f"\n  Ocurrió un error inesperado al leer el archivo: {e}")

"""#2. Limpieza del dataset
   Realiza la limpieza completa del DataFrame:
      - Normaliza nombres de columnas
      - Elimina filas completamente vacías o duplicadas
      - Convierte la columna Fecha al tipo datetime
      - Convierte los tipos de cambio a valores numéricos
      - Elimina filas con valores nulos en columnas clave

    Parámetros:
        df (DataFrame): DataFrame crudo

    Retorna:
        DataFrame limpio
"""

#Limpieza de los Datos

def limpiar_datos(df):

    df = df.copy()

    # --- 2.1 Limpiar nombres de columnas ---
    # Quitar espacios, pasar a minúsculas, reemplazar caracteres especiales
    df.columns = (
        df.columns
        .str.strip()
        .str.lower()
        .str.replace('á', 'a').str.replace('é', 'e')
        .str.replace('í', 'i').str.replace('ó', 'o')
        .str.replace('ú', 'u')
        .str.replace(' ', '_')
        .str.replace('.', '_')
    )

    print("\n Columnas después de limpiar nombres:")
    print(list(df.columns))

    # --- 2.2 Renombrar columnas a nombres estándar ---
    # Buscar columnas que contengan palabras clave
    mapa_columnas = {}
    for col in df.columns:
        if 'fecha' in col or 'date' in col:
            mapa_columnas[col] = 'fecha'
        elif 'compra' in col or 'buy' in col or 'bid' in col:
            mapa_columnas[col] = 'compra'
        elif 'venta' in col or 'sell' in col or 'ask' in col:
            mapa_columnas[col] = 'venta'

    df = df.rename(columns=mapa_columnas)

    # Verificar que existen las columnas necesarias
    columnas_requeridas = ['fecha', 'compra', 'venta']
    for col in columnas_requeridas:
        if col not in df.columns:
            raise ValueError(f" No se encontró la columna '{col}'. "
                             f"Columnas disponibles: {list(df.columns)}")

    # Seleccionar solo las columnas necesarias
    df = df[columnas_requeridas].copy()

    # --- 2.3 Eliminar filas completamente vacías o duplicadas ---
    filas_antes = len(df)
    df = df.dropna(how='all')         # eliminar filas donde TODO es nulo
    df = df.drop_duplicates()          # eliminar duplicados exactos
    print(f"\n  Filas eliminadas (vacías/duplicadas): {filas_antes - len(df)}")

    # --- 2.4 Convertir columna 'fecha' a datetime ---
    # Intentar múltiples formatos comunes en archivos del BCCR
    formatos_fecha = ['%d/%m/%Y', '%Y-%m-%d', '%d-%m-%Y', '%m/%d/%Y', '%d/%m/%y']
    convertida = False

    for fmt in formatos_fecha:
        try:
            df['fecha'] = pd.to_datetime(df['fecha'], format=fmt)
            print(f" Fechas convertidas con formato: '{fmt}'")
            convertida = True
            break
        except Exception:
            continue

    if not convertida:
        # Último recurso: dejar que pandas lo infiera automáticamente
        df['fecha'] = pd.to_datetime(df['fecha'], infer_datetime_format=True, errors='coerce')
        print("  Fechas convertidas con inferencia automática")

    # --- 2.5 Convertir tipos de cambio a numéricos ---
    for col in ['compra', 'venta']:
        # Eliminar símbolos comunes: ₡, $, espacios, puntos de miles
        df[col] = (
            df[col].astype(str)
            .str.replace('₡', '', regex=False)
            .str.replace('$', '', regex=False)
            .str.replace(' ', '', regex=False)
            .str.replace(',', '.', regex=False)  # coma decimal → punto
        )
        df[col] = pd.to_numeric(df[col], errors='coerce')

    # --- 2.6 Filtrar el período 2018-2025 ---
    df = df[(df['fecha'].dt.year >= 2018) & (df['fecha'].dt.year <= 2025)]

    # --- 2.7 Eliminar filas con nulos en columnas clave ---
    filas_antes = len(df)
    df = df.dropna(subset=['fecha', 'compra', 'venta'])
    print(f"  Filas eliminadas (valores inválidos): {filas_antes - len(df)}")

    # --- 2.8 Ordenar por fecha ---
    df = df.sort_values('fecha').reset_index(drop=True)

    return df


# Ejecutar limpieza
df = limpiar_datos(df_crudo)

print(f"\n Dataset limpio: {df.shape[0]} registros válidos")
print("\n Primeras filas del dataset limpio:")
print(df.head())
print("\n Últimas filas del dataset limpio:")
print(df.tail())
print(f"\n Período cubierto: {df['fecha'].min().date()} → {df['fecha'].max().date()}")

"""#3. Creamos una nueva variable que contenga el tipo de cambio promedio"""

#Creacion de nueva variable - TIPO DE CAMBIO PROMEDIO

print("\n" + "="*60)
print("SECCIÓN 3: CREACIÓN DE VARIABLE PROMEDIO")
print("="*60)

# Calcular el promedio entre compra y venta (spread medio)
# Este valor representa el punto medio del mercado cambiario
df['promedio'] = (df['compra'] + df['venta']) / 2

print(" Variable 'promedio' creada (media entre compra y venta)")
print(df[['fecha', 'compra', 'venta', 'promedio']].head(10))

"""#4. Creamos los datos de ser diarios a mensuales"""

# Transformación de datos diarios a mensuales

print("\n" + "="*60)
print("SECCIÓN 4: AGREGACIÓN MENSUAL")
print("="*60)

# Crear columna de año-mes para agrupar
df['anio_mes'] = df['fecha'].dt.to_period('M')

# Agregar por mes: calcular el promedio mensual de cada variable
df_mensual = (
    df.groupby('anio_mes')[['compra', 'venta', 'promedio']]
    .mean()
    .round(2)
    .reset_index()
)

# Convertir el período a fecha (primer día del mes) para graficar
df_mensual['fecha'] = df_mensual['anio_mes'].dt.to_timestamp()

print(f" Datos agregados: {len(df_mensual)} meses")
print("\n Primeras filas del dataset mensual:")
print(df_mensual[['fecha', 'compra', 'venta', 'promedio']].head(12))

"""#5. Creación de gráficas y exploración de las estadisticas descriptivas mensuales"""

# ============================================================
# SECCIÓN 5: ANÁLISIS EXPLORATORIO - GRÁFICAS COMPLETAS
# ============================================================


# ── GRÁFICA 1: Serie de tiempo ──────
fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(df_mensual['fecha'], df_mensual['compra'],
        color='#2196F3', linewidth=1.5, alpha=0.7, label='Compra')
ax.plot(df_mensual['fecha'], df_mensual['venta'],
        color='#F44336', linewidth=1.5, alpha=0.7, label='Venta')
ax.plot(df_mensual['fecha'], df_mensual['promedio'],
        color='#4CAF50', linewidth=2.5, label='Promedio', zorder=5)
ax.fill_between(df_mensual['fecha'], df_mensual['compra'], df_mensual['venta'],
                alpha=0.15, color='gray', label='Spread compra/venta')

ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
plt.xticks(rotation=45, ha='right')
ax.set_title('Evolución del Tipo de Cambio USD/CRC (2018–2025)\nFuente: BCCR',
             fontsize=14, fontweight='bold', pad=15)

ax.set_xlabel('Mes')
ax.set_ylabel('Tipo de Cambio (₡ por USD)')
ax.legend(loc='upper left')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))
plt.tight_layout()
plt.savefig('evolucion_tipo_cambio.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica 1 guardada: evolucion_tipo_cambio.png")


# ── GRÁFICA 2: Histograma ────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 6))
ax.hist(df_mensual['promedio'], bins=20,
        color='#2196F3', edgecolor='white', alpha=0.85)
ax.axvline(df_mensual['promedio'].mean(), color='#F44336',
           linestyle='--', linewidth=2,
           label=f"Media: ₡{df_mensual['promedio'].mean():,.0f}")
ax.axvline(df_mensual['promedio'].median(), color='#4CAF50',
           linestyle='-.', linewidth=2,
           label=f"Mediana: ₡{df_mensual['promedio'].median():,.0f}")
ax.set_title('Distribución del Tipo de Cambio USD/CRC (2018–2025)',
             fontsize=13, fontweight='bold')
ax.set_xlabel('Tipo de Cambio (₡ por USD)', fontsize=11)
ax.set_ylabel('Frecuencia (número de meses)', fontsize=11)
ax.legend(fontsize=10)
ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))
plt.tight_layout()
plt.savefig('histograma_tipo_cambio.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica 2 guardada: histograma_tipo_cambio.png")


# ── GRÁFICA 3: Boxplot ───────────────────────────────────────
fig, ax = plt.subplots(figsize=(7, 8))
bp = ax.boxplot(df_mensual['promedio'],
                patch_artist=True,
                medianprops=dict(color='#F44336', linewidth=2.5),
                boxprops=dict(facecolor='#BBDEFB', color='#1565C0'),
                whiskerprops=dict(color='#1565C0', linewidth=1.5),
                capprops=dict(color='#1565C0', linewidth=2),
                flierprops=dict(marker='o', color='#FF7043',
                                markerfacecolor='#FF7043', markersize=7))
stats = df_mensual['promedio'].describe()
ax.annotate(f"Mediana: ₡{stats['50%']:,.0f}",
            xy=(1, stats['50%']), xytext=(1.12, stats['50%']),
            fontsize=9, color='#F44336')
ax.annotate(f"Q3: ₡{stats['75%']:,.0f}",
            xy=(1, stats['75%']), xytext=(1.12, stats['75%'] + 2),
            fontsize=9, color='#1565C0')
ax.annotate(f"Q1: ₡{stats['25%']:,.0f}",
            xy=(1, stats['25%']), xytext=(1.12, stats['25%'] - 6),
            fontsize=9, color='#1565C0')
ax.set_title('Boxplot – Tipo de Cambio USD/CRC (2018–2025)',
             fontsize=13, fontweight='bold')
ax.set_ylabel('Tipo de Cambio (₡ por USD)', fontsize=11)
ax.set_xticks([])
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))
plt.tight_layout()
plt.savefig('boxplot_tipo_cambio.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica 3 guardada: boxplot_tipo_cambio.png")

#  Verificación de la media, mediana, min, max, etc
print (f"Estadisticas descriptivas mensuales")
df_mensual['promedio'].describe()

"""#6. Creacion de los modelos matemáticos utilizados"""

# Aplicación de modelos matemáticos

print("\n" + "="*60)
print("SECCIÓN 6: AJUSTE DE MODELOS MATEMÁTICOS")
print("="*60)

# --- 6.1 Preparar variable independiente (X) ---
# Convertimos las fechas a un número entero (meses desde el inicio)
# Esto es necesario porque los modelos matemáticos trabajan con números, no fechas

fecha_inicio = df_mensual['fecha'].min()
df_mensual['mes_num'] = (
    (df_mensual['fecha'].dt.year - fecha_inicio.year) * 12
    + (df_mensual['fecha'].dt.month - fecha_inicio.month)
)

X = df_mensual['mes_num'].values.reshape(-1, 1)  # forma requerida por sklearn
y = df_mensual['promedio'].values                  # variable objetivo

print(f" Variable X: meses desde {fecha_inicio.strftime('%Y-%m')} "
      f"(0 a {int(X.max())})")
print(f" Variable y: tipo de cambio promedio mensual")

# --- 6.2 Modelo 1: Regresión Lineal ---
modelo_lineal = LinearRegression()
modelo_lineal.fit(X, y)
y_pred_lineal = modelo_lineal.predict(X)
r2_lineal = r2_score(y, y_pred_lineal)

print(f"\n Modelo Lineal:")
print(f"   Ecuación: y = {modelo_lineal.coef_[0]:.4f}·x + {modelo_lineal.intercept_:.2f}")
print(f"   Interpretación: el tipo de cambio sube ~₡{modelo_lineal.coef_[0]:.2f} por mes")
print(f"   R² = {r2_lineal:.4f} ({r2_lineal*100:.2f}% de varianza explicada)")

# --- 6.3 Modelo 2: Regresión Polinomial Grado 2
modelo_poly2 = make_pipeline(PolynomialFeatures(degree=2), LinearRegression())
modelo_poly2.fit(X, y)
y_pred_poly2 = modelo_poly2.predict(X)
r2_poly2 = r2_score(y, y_pred_poly2)

print(f"\n Modelo Polinomial Grado 2:")
print(f"   R² = {r2_poly2:.4f} ({r2_poly2*100:.2f}% de varianza explicada)")

# --- 6.4 Modelo 3: Regresión Polinomial Grado 3
modelo_poly3 = make_pipeline(PolynomialFeatures(degree=3), LinearRegression())
modelo_poly3.fit(X, y)
y_pred_poly3 = modelo_poly3.predict(X)
r2_poly3 = r2_score(y, y_pred_poly3)

print(f"\n Modelo Polinomial Grado 3:")
print(f"   R² = {r2_poly3:.4f} ({r2_poly3*100:.2f}% de varianza explicada)")

"""#7. Comparación de los modelos y calcular el R^2 de cada modelo."""

# Comparación de modelos

print("\n" + "="*60)
print("SECCIÓN 7: COMPARACIÓN DE MODELOS")
print("="*60)

# Crear tabla comparativa
resultados = {
    'Modelo': ['Lineal', 'Polinomial Grado 2', 'Polinomial Grado 3'],
    'R²': [r2_lineal, r2_poly2, r2_poly3],
    'R² (%)': [f"{r2_lineal*100:.2f}%", f"{r2_poly2*100:.2f}%", f"{r2_poly3*100:.2f}%"],
    'Complejidad': ['Baja', 'Media', 'Alta'],
}
df_resultados = pd.DataFrame(resultados)
print("\n" + df_resultados.to_string(index=False))

# Identificar el mejor modelo
mejor_r2 = max(r2_lineal, r2_poly2, r2_poly3)
if mejor_r2 == r2_lineal:
    mejor_modelo_nombre = "Lineal"
    mejor_modelo = modelo_lineal
    mejor_pred = y_pred_lineal
elif mejor_r2 == r2_poly2:
    mejor_modelo_nombre = "Polinomial Grado 2"
    mejor_modelo = modelo_poly2
    mejor_pred = y_pred_poly2
else:
    mejor_modelo_nombre = "Polinomial Grado 3"
    mejor_modelo = modelo_poly3
    mejor_pred = y_pred_poly3

print(f"\n Mejor modelo: {mejor_modelo_nombre} (R² = {mejor_r2:.4f})")
print("   Nota: Un R² más cercano a 1.0 indica mejor ajuste.")
print("   Sin embargo, modelos más complejos pueden sobreajustarse (overfitting).")

# Advertencia sobre sobreajuste
if mejor_modelo_nombre == "Polinomial Grado 3":
    print("\n  Advertencia: El grado 3 puede sobreajustarse. "
          "Considere el grado 2 si la diferencia de R² es pequeña.")

"""#8. Creación de gráfico comparativo de datos reales vs modelos"""

# Visualización de datos ajustados

print("\n" + "="*60)
print("SECCIÓN 8: VISUALIZACIÓN COMPARATIVA DE MODELOS")
print("="*60)

fig, ax = plt.subplots(figsize=(14, 7))

# Datos reales
ax.scatter(df_mensual['fecha'], y,
           color='#333333', s=30, alpha=0.6, zorder=5, label='Datos reales (mensual)')

# Curvas ajustadas
ax.plot(df_mensual['fecha'], y_pred_lineal,
        color='#2196F3', linewidth=2, linestyle='--',
        label=f'Lineal (R²={r2_lineal:.3f})')

ax.plot(df_mensual['fecha'], y_pred_poly2,
        color='#FF9800', linewidth=2, linestyle='-.',
        label=f'Polinomial Grado 2 (R²={r2_poly2:.3f})')

ax.plot(df_mensual['fecha'], y_pred_poly3,
        color='#9C27B0', linewidth=2, linestyle=':',
        label=f'Polinomial Grado 3 (R²={r2_poly3:.3f})')

# Formato
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
plt.xticks(rotation=45, ha='right')

ax.set_title('Tipo de Cambio USD/CRC: Datos Reales vs Modelos Ajustados\nFuente: BCCR',
             fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Mes')
ax.set_ylabel('Tipo de Cambio Promedio (₡ por USD)')
ax.legend(loc='upper left')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))

plt.tight_layout()
plt.savefig('modelos_ajustados.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica guardada como 'modelos_ajustados.png'")

"""#9. Creación modelo de proyección a 5 meses"""

# Modelo de proyección a 5 meses

print("\n" + "="*60)
print("SECCIÓN 9: PROYECCIÓN A 5 MESES")
print("="*60)

# --- 9.1 Generar meses futuros ---
ultimo_mes_num = int(X.max())
ultimo_mes_fecha = df_mensual['fecha'].max()

meses_futuros_num = np.array(
    [ultimo_mes_num + i for i in range(1, 6)]
).reshape(-1, 1)

# Generar fechas futuras (próximos 5 meses)
fechas_futuras = pd.date_range(
    start=ultimo_mes_fecha + pd.DateOffset(months=1),
    periods=5,
    freq='MS'  # MS = inicio de mes
)

# --- 9.2 Proyección con el mejor modelo ---
proyecciones = mejor_modelo.predict(meses_futuros_num)

# Crear tabla de proyecciones
df_proyeccion = pd.DataFrame({
    'Mes':          fechas_futuras.strftime('%B %Y'),
    'Proyección (₡)': [f"₡{p:,.2f}" for p in proyecciones],
    'Variación':    [f"{((proyecciones[i]-proyecciones[i-1])/proyecciones[i-1]*100):+.2f}%"
                     if i > 0 else "—" for i in range(5)]
})

print(f"\n Proyección con modelo {mejor_modelo_nombre}:\n")
print(df_proyeccion.to_string(index=False))

# --- 9.3 Gráfica con proyección ---
fig, ax = plt.subplots(figsize=(14, 7))

# Datos históricos reales
ax.plot(df_mensual['fecha'], y,
        color='#333333', linewidth=2, label='Datos reales')

# Ajuste del mejor modelo sobre datos históricos
ax.plot(df_mensual['fecha'], mejor_pred,
        color='#2196F3', linewidth=2, linestyle='--',
        label=f'Ajuste {mejor_modelo_nombre}', alpha=0.8)

# Proyección futura
ax.plot(fechas_futuras, proyecciones,
        color='#F44336', linewidth=2.5, linestyle='-',
        marker='o', markersize=8, label='Proyección (5 meses)')

# Línea divisoria entre histórico y proyección
ax.axvline(x=ultimo_mes_fecha, color='gray',
           linestyle=':', linewidth=1.5, alpha=0.8, label='Hoy')

# Sombrear área de proyección
ax.axvspan(ultimo_mes_fecha, fechas_futuras[-1],
           alpha=0.08, color='red', label='Período proyectado')

# Etiquetas en los puntos proyectados
for fecha, valor in zip(fechas_futuras, proyecciones):
    ax.annotate(f'₡{valor:,.0f}',
                xy=(fecha, valor),
                xytext=(0, 12),
                textcoords='offset points',
                ha='center', fontsize=9,
                color='#C62828', fontweight='bold')

# Formato del eje X
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
plt.xticks(rotation=45, ha='right')

ax.set_title(f'Proyección del Tipo de Cambio USD/CRC (Próximos 5 meses)\n'
             f'Modelo: {mejor_modelo_nombre} | R²={mejor_r2:.4f} | Fuente: BCCR',
             fontsize=13, fontweight='bold', pad=15)
ax.set_xlabel('Mes')
ax.set_ylabel('Tipo de Cambio Promedio (₡ por USD)')
ax.legend(loc='upper left')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))

plt.tight_layout()
plt.savefig('proyeccion_tipo_cambio.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica guardada como 'proyeccion_tipo_cambio.png'")

# --- 9.4 Resumen final ---
print("\n" + "="*60)
print("RESUMEN FINAL DEL ANÁLISIS")
print("="*60)
print(f"  Período analizado:    {df['fecha'].min().strftime('%B %Y')} → "
      f"{df['fecha'].max().strftime('%B %Y')}")
print(f"  Registros diarios:    {len(df):,}")
print(f"  Meses analizados:     {len(df_mensual)}")
print(f"  Tipo de cambio inicio:{y[0]:>10,.2f} ₡/USD")
print(f"  Tipo de cambio final: {y[-1]:>10,.2f} ₡/USD")
print(f"  Mejor modelo:         {mejor_modelo_nombre} (R²={mejor_r2:.4f})")
print(f"  Proyección 5 meses:   {proyecciones[0]:,.2f} → {proyecciones[-1]:,.2f} ₡/USD")
print("\n Análisis completo. Revisa las gráficas generadas.")
print("  Nota: Las proyecciones son estimaciones basadas en tendencias históricas.")
print("    No deben usarse como asesoría financiera.")

"""#Implementación de Arima"""

#Instalar librerias

!pip install pmdarima --quiet

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import warnings
warnings.filterwarnings('ignore')

# Librerías para series de tiempo
from statsmodels.tsa.stattools import adfuller          # Prueba ADF
from statsmodels.tsa.arima.model import ARIMA           # Modelo ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf  # Gráficas ACF/PACF
import pmdarima as pm                                   # auto_arima

# Métricas de evaluación
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Configuración visual
plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['font.size'] = 12
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.4

print(" Librerías cargadas correctamente")
print("=" * 60)

# Preparación de la serie de tiempo

print("\n" + "=" * 60)
print("SECCIÓN A: PREPARACIÓN DE LA SERIE DE TIEMPO")
print("=" * 60)

# --- A.1 Crear una copia de trabajo para no alterar df_mensual original ---
ts = df_mensual[['fecha', 'promedio']].copy()

# --- A.2 Establecer 'fecha' como índice del DataFrame ---
# Esto es obligatorio para que statsmodels reconozca la serie temporal
ts = ts.set_index('fecha')

# --- A.3 Asegurar frecuencia mensual 'MS' (Month Start) ---
# Si hay fechas faltantes, se rellenan con NaN y luego se interpolan
ts = ts.asfreq('MS')

# --- A.4 Verificar y manejar valores nulos ---
nulos = ts['promedio'].isnull().sum()
if nulos > 0:
    print(f"  Se encontraron {nulos} valores nulos. Se interpolará linealmente.")
    ts['promedio'] = ts['promedio'].interpolate(method='linear')
else:
    print(" No hay valores nulos en la serie.")

# --- A.5 Resumen de la serie preparada ---
print(f"\n Serie de tiempo lista:")
print(f"   Período:       {ts.index.min().strftime('%Y-%m')} → {ts.index.max().strftime('%Y-%m')}")
print(f"   Observaciones: {len(ts)}")
print(f"   Frecuencia:    Mensual (MS)")
print(f"   Mínimo:        ₡{ts['promedio'].min():,.2f}")
print(f"   Máximo:        ₡{ts['promedio'].max():,.2f}")
print(f"   Promedio:      ₡{ts['promedio'].mean():,.2f}")

# Visualización inicial de la serie

print("\n" + "=" * 60)
print("SECCIÓN B: VISUALIZACIÓN DE LA SERIE TEMPORAL")
print("=" * 60)

fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(ts.index, ts['promedio'],
        color='#1565C0', linewidth=2, label='Tipo de cambio promedio')
ax.fill_between(ts.index, ts['promedio'],
                ts['promedio'].min() * 0.99,
                alpha=0.1, color='#1565C0')

# Marcar máximo y mínimo histórico
idx_max = ts['promedio'].idxmax()
idx_min = ts['promedio'].idxmin()
ax.scatter([idx_max], [ts['promedio'].max()],
           color='red', s=80, zorder=5, label=f"Máx: ₡{ts['promedio'].max():,.0f}")
ax.scatter([idx_min], [ts['promedio'].min()],
           color='green', s=80, zorder=5, label=f"Mín: ₡{ts['promedio'].min():,.0f}")

ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
plt.xticks(rotation=45, ha='right')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))
ax.set_title('Serie Temporal: Tipo de Cambio USD/CRC (Promedio Mensual)\nFuente: BCCR',
             fontsize=14, fontweight='bold')
ax.set_xlabel('Mes')
ax.set_ylabel('₡ por USD')
ax.legend()
plt.tight_layout()
plt.savefig('arima_serie_original.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica guardada: 'arima_serie_original.png'")

# Prueba ADF, verificación de estacionariedad
"""
 Una serie es ESTACIONARIA si su media y varianza no cambian en el tiempo.
 ARIMA requiere que la serie sea estacionaria (o que la hagamos estacionaria).
 La prueba ADF (Augmented Dickey-Fuller) verifica esto estadísticamente:
  - H0 (hipótesis nula):  la serie NO es estacionaria (tiene raíz unitaria)
  - Si p-value < 0.05 → rechazamos H0 → la serie SÍ es estacionaria

"""

print("\n" + "=" * 60)
print("SECCIÓN C: PRUEBA DE ESTACIONARIEDAD (ADF)")
print("=" * 60)

def prueba_adf(serie, nombre="Serie"):
    """
    Aplica la prueba Augmented Dickey-Fuller a una serie.

    Parámetros:
        serie  (Series): serie de tiempo a evaluar
        nombre (str):    nombre descriptivo para mostrar en el resultado

    Retorna:
        es_estacionaria (bool): True si la serie es estacionaria
    """
    resultado = adfuller(serie.dropna(), autolag='AIC')
    estadistico = resultado[0]
    p_valor      = resultado[1]
    valores_crit = resultado[4]

    print(f"\n   Prueba ADF – {nombre}")
    print(f"  {'─'*45}")
    print(f"  Estadístico ADF:   {estadistico:.4f}")
    print(f"  p-value:           {p_valor:.4f}")
    print(f"  Valor crítico 1%:  {valores_crit['1%']:.4f}")
    print(f"  Valor crítico 5%:  {valores_crit['5%']:.4f}")
    print(f"  Valor crítico 10%: {valores_crit['10%']:.4f}")

    es_estacionaria = p_valor < 0.05
    if es_estacionaria:
        print(f"\n   La serie ES estacionaria (p-value = {p_valor:.4f} < 0.05)")
        print("     No se necesita diferenciación.")
    else:
        print(f"\n   La serie NO es estacionaria (p-value = {p_valor:.4f} ≥ 0.05)")
        print("     Se aplicará diferenciación (d=1).")

    return es_estacionaria


# Probar la serie original
es_estacionaria = prueba_adf(ts['promedio'], nombre="Serie Original")

#Diferenciación

"""
La diferenciación elimina tendencias haciendo: y'(t) = y(t) - y(t-1)
Esto convierte una serie no estacionaria en estacionaria.
El parámetro 'd' en ARIMA indica cuántas veces se diferencia.
"""

print("\n" + "=" * 60)
print("SECCIÓN D: DIFERENCIACIÓN (si aplica)")
print("=" * 60)

d_optimo = 0  # valor inicial

if not es_estacionaria:
    print("\n Aplicando diferenciación de orden 1...")
    ts['promedio_diff'] = ts['promedio'].diff()

    # Probar estacionariedad sobre la serie diferenciada
    es_estacionaria_diff = prueba_adf(
        ts['promedio_diff'].dropna(),
        nombre="Serie Diferenciada (d=1)"
    )
    d_optimo = 1

    if not es_estacionaria_diff:
        print("\n  Aún no es estacionaria. Aplicando diferenciación de orden 2...")
        ts['promedio_diff2'] = ts['promedio_diff'].diff()
        prueba_adf(ts['promedio_diff2'].dropna(), nombre="Serie Diferenciada (d=2)")
        d_optimo = 2

    # Gráfica comparativa: original vs diferenciada
    fig, axes = plt.subplots(2, 1, figsize=(14, 8))

    axes[0].plot(ts.index, ts['promedio'], color='#1565C0', linewidth=2)
    axes[0].set_title('Serie Original (No estacionaria)', fontweight='bold')
    axes[0].set_ylabel('₡ por USD')
    axes[0].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))

    axes[1].plot(ts.index, ts['promedio_diff'], color='#E65100', linewidth=1.5)
    axes[1].axhline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)
    axes[1].set_title('Serie Diferenciada d=1 (Estacionaria)', fontweight='bold')
    axes[1].set_ylabel('Cambio mensual (₡)')
    axes[1].yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))

    for ax in axes:
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
        ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
        plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha='right')
        ax.grid(True, alpha=0.4)

    plt.tight_layout()
    plt.savefig('arima_diferenciacion.png', dpi=150, bbox_inches='tight')
    plt.show()
    print(" Gráfica guardada: 'arima_diferenciacion.png'")

else:
    print("\n No se requiere diferenciación (d=0)")
    d_optimo = 0

#Selección automática de parámetros con auto_arima
"""
ARIMA(p, d, q) tiene tres parámetros:
p = orden autorregresivo (cuántos rezagos del pasado usar)
d = grado de diferenciación (ya lo determinamos arriba)
q = orden de la media móvil (cuántos errores pasados incluir)

auto_arima prueba múltiples combinaciones y elige la que minimiza el AIC
(Akaike Information Criterion): entre menor AIC, mejor el modelo.
"""


print("\n" + "=" * 60)
print("SECCIÓN E: SELECCIÓN AUTOMÁTICA DE PARÁMETROS (auto_arima)")
print("=" * 60)

print("\n Buscando los mejores parámetros p, d, q...")
print("   (Esto puede tardar 30–60 segundos)\n")

modelo_auto = pm.auto_arima(
    ts['promedio'],
    d=d_optimo,          # usar el d determinado por la prueba ADF
    start_p=0,           # valor mínimo de p a probar
    start_q=0,           # valor mínimo de q a probar
    max_p=5,             # valor máximo de p a probar
    max_q=5,             # valor máximo de q a probar
    seasonal=False,      # sin componente estacional (SARIMA)
    stepwise=True,       # búsqueda eficiente (no prueba todas las combinaciones)
    information_criterion='aic',   # criterio de selección
    error_action='ignore',
    suppress_warnings=True,
    trace=True           # mostrar qué combinaciones se prueban
)

# Extraer los parámetros óptimos
p_opt, d_opt, q_opt = modelo_auto.order
print(f"\n{'='*45}")
print(f" Parámetros óptimos encontrados: ARIMA({p_opt}, {d_opt}, {q_opt})")
print(f"   AIC del modelo seleccionado: {modelo_auto.aic():.2f}")
print(f"{'='*45}")
print("""
   Interpretación de parámetros:
   ─────────────────────────────────────────────
   p = {} → El modelo usa los últimos {} meses
             de datos para predecir el siguiente
   d = {} → La serie fue diferenciada {} vez(ces)
             para hacerla estacionaria
   q = {} → Se usan los últimos {} errores de
             predicción para corregir el modelo
""".format(p_opt, p_opt, d_opt, d_opt, q_opt, q_opt))

# Entrenamiento con prueba 80%/20%
"""
Separamos los datos para evaluar qué tan bien predice el modelo
en datos que NO vio durante el entrenamiento (datos de prueba).
Esto evita el "sobreajuste" (overfitting) y da una evaluación honesta.
"""

print("\n" + "=" * 60)
print("SECCIÓN F: DIVISIÓN ENTRENAMIENTO / PRUEBA (80% / 20%)")
print("=" * 60)

n_total     = len(ts)
n_train     = int(n_total * 0.80)   # 80% para entrenar
n_test      = n_total - n_train     # 20% para evaluar

ts_train = ts['promedio'].iloc[:n_train]   # datos de entrenamiento
ts_test  = ts['promedio'].iloc[n_train:]   # datos de prueba (no vistos)

print(f"\n  Total de observaciones: {n_total} meses")
print(f"  Entrenamiento (80%):    {n_train} meses "
      f"({ts_train.index.min().strftime('%Y-%m')} → {ts_train.index.max().strftime('%Y-%m')})")
print(f"  Prueba (20%):           {n_test} meses "
      f"({ts_test.index.min().strftime('%Y-%m')} → {ts_test.index.max().strftime('%Y-%m')})")

# Entrenamiento de Arima

print("\n" + "=" * 60)
print("SECCIÓN G: ENTRENAMIENTO DEL MODELO ARIMA")
print("=" * 60)

print(f"\n  Entrenando ARIMA({p_opt}, {d_opt}, {q_opt}) con datos de entrenamiento...")

modelo_arima = ARIMA(
    ts_train,
    order=(p_opt, d_opt, q_opt)
)
resultado_arima = modelo_arima.fit()

print(" Modelo entrenado exitosamente.")

# Resumen del Modelo

print("\n" + "=" * 60)
print("SECCIÓN H: RESUMEN ESTADÍSTICO DEL MODELO")
print("=" * 60)

print(resultado_arima.summary())

print("""
   Cómo interpretar el resumen:
  ──────────────────────────────────────────────────────────
  • coef      : valor del parámetro estimado
  • P>|z|     : p-value del parámetro
                → si < 0.05, el parámetro es estadísticamente
                  significativo (aporta al modelo)
  • AIC / BIC : criterios de información. Menor = mejor modelo
  • Log Lik.  : log-verosimilitud. Mayor = mejor ajuste
  ──────────────────────────────────────────────────────────
""")

# Evaluación del Conjunto de prueba

print("\n" + "=" * 60)
print("SECCIÓN I: EVALUACIÓN EN CONJUNTO DE PRUEBA")
print("=" * 60)

# Predecir exactamente los n_test pasos del conjunto de prueba
pred_test = resultado_arima.forecast(steps=n_test)
pred_test.index = ts_test.index   # asignar las fechas correctas

# --- Calcular métricas de error ---
mae  = mean_absolute_error(ts_test, pred_test)
rmse = np.sqrt(mean_squared_error(ts_test, pred_test))
mape = np.mean(np.abs((ts_test.values - pred_test.values) / ts_test.values)) * 100

print(f"\n   Métricas de evaluación sobre el conjunto de PRUEBA:")
print(f"  {'─'*50}")
print(f"  MAE  (Error Absoluto Medio):       ₡{mae:>10,.2f}")
print(f"  RMSE (Raíz del Error Cuadrático):  ₡{rmse:>10,.2f}")
print(f"  MAPE (Error Porcentual Medio):      {mape:>9.2f}%")
print(f"  {'─'*50}")

# Interpretación automática del MAPE
print("\n   Interpretación del MAPE:")
if mape < 5:
    calidad = "Excelente"
    emoji = "🟢"
    detalle = "El modelo predice con muy alta precisión."
elif mape < 10:
    calidad = "Buena"
    emoji = "🟡"
    detalle = "El modelo es preciso y útil para proyecciones."
elif mape < 20:
    calidad = "Aceptable"
    emoji = "🟠"
    detalle = "Hay margen de mejora. Considerar más datos o ajustar parámetros."
else:
    calidad = "Deficiente"
    emoji = "🔴"
    detalle = "El modelo tiene baja precisión. Revisar parámetros o usar otro enfoque."

print(f"  {emoji} Calidad del modelo: {calidad} (MAPE = {mape:.2f}%)")
print(f"     {detalle}")

# --- Tabla comparativa: real vs predicho ---
df_comparacion = pd.DataFrame({
    'Mes':           ts_test.index.strftime('%Y-%m'),
    'Real (₡)':      ts_test.values.round(2),
    'Predicho (₡)':  pred_test.values.round(2),
    'Error (₡)':     (pred_test.values - ts_test.values).round(2),
    'Error (%)':     ((pred_test.values - ts_test.values) / ts_test.values * 100).round(2)
})
print(f"\n   Comparación real vs predicho (conjunto de prueba):\n")
print(df_comparacion.to_string(index=False))

# Predicción para los próximos 5 meses

"""
Ahora reentrenamos el modelo con TODOS los datos (no solo el 80%)
para hacer la proyección futura con la mejor información disponible.
"""

print("\n" + "=" * 60)
print("SECCIÓN J: PROYECCIÓN FUTURA (5 MESES) CON ARIMA")
print("=" * 60)

print("\n  Reentrenando ARIMA con todos los datos para proyección futura...")

modelo_final = ARIMA(ts['promedio'], order=(p_opt, d_opt, q_opt))
resultado_final = modelo_final.fit()

# Predecir 5 meses hacia adelante
MESES_FUTURO = 5
pronostico = resultado_final.get_forecast(steps=MESES_FUTURO)

# Obtener valores y el intervalo de confianza al 95%
pred_media = pronostico.predicted_mean
conf_int   = pronostico.conf_int(alpha=0.05)   # intervalo 95%

# Generar fechas futuras
ultima_fecha    = ts.index.max()
fechas_futuras  = pd.date_range(
    start=ultima_fecha + pd.DateOffset(months=1),
    periods=MESES_FUTURO,
    freq='MS'
)
pred_media.index = fechas_futuras
conf_int.index   = fechas_futuras

# Tabla de proyección
df_proyeccion_arima = pd.DataFrame({
    'Mes':                fechas_futuras.strftime('%B %Y'),
    'Predicción ARIMA':   pred_media.values.round(2),
    'Límite Inferior 95%': conf_int.iloc[:, 0].values.round(2),
    'Límite Superior 95%': conf_int.iloc[:, 1].values.round(2),
})

print(f"\n   Proyección ARIMA({p_opt},{d_opt},{q_opt}) — próximos {MESES_FUTURO} meses:\n")
print(df_proyeccion_arima.to_string(index=False))
print("\n  ℹ  El intervalo de confianza al 95% indica el rango donde")
print("      se espera que caiga el valor real con 95% de probabilidad.")

# Visualización completa

print("\n" + "=" * 60)
print("SECCIÓN K: VISUALIZACIÓN COMPLETA")
print("=" * 60)

# --- Gráfica 1: Evaluación en datos de prueba ---
fig, ax = plt.subplots(figsize=(14, 6))

# Datos de entrenamiento
ax.plot(ts_train.index, ts_train,
        color='#1565C0', linewidth=2, label='Entrenamiento (80%)')

# Datos de prueba (reales)
ax.plot(ts_test.index, ts_test,
        color='#2E7D32', linewidth=2, label='Prueba real (20%)')

# Predicción sobre prueba
ax.plot(pred_test.index, pred_test,
        color='#F57F17', linewidth=2, linestyle='--',
        label=f'ARIMA({p_opt},{d_opt},{q_opt}) sobre prueba')

# Rellenar diferencia entre real y predicho
ax.fill_between(ts_test.index,
                ts_test.values,
                pred_test.values,
                alpha=0.2, color='red', label='Error de predicción')

# Línea divisoria entrenamiento/prueba
ax.axvline(x=ts_test.index[0], color='gray',
           linestyle=':', linewidth=2, alpha=0.8, label='Inicio del período de prueba')

ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=4))
plt.xticks(rotation=45, ha='right')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))
ax.set_title(f'ARIMA({p_opt},{d_opt},{q_opt}): Evaluación en Conjunto de Prueba\n'
             f'MAE=₡{mae:,.0f} | RMSE=₡{rmse:,.0f} | MAPE={mape:.2f}%',
             fontsize=13, fontweight='bold')
ax.set_xlabel('Mes')
ax.set_ylabel('₡ por USD')
ax.legend(loc='upper left')
plt.tight_layout()
plt.savefig('arima_evaluacion_prueba.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica guardada: 'arima_evaluacion_prueba.png'")

# --- Gráfica 2: Proyección futura con intervalo de confianza ---
fig, ax = plt.subplots(figsize=(14, 6))

# Mostrar solo los últimos 24 meses de historia para más claridad
ts_reciente = ts['promedio'].iloc[-24:]

ax.plot(ts_reciente.index, ts_reciente,
        color='#1565C0', linewidth=2.5, label='Datos históricos (últimos 24 meses)')

# Proyección futura
ax.plot(fechas_futuras, pred_media,
        color='#D32F2F', linewidth=2.5, linestyle='-',
        marker='o', markersize=8, label='Proyección ARIMA (5 meses)')

# Intervalo de confianza al 95%
ax.fill_between(fechas_futuras,
                conf_int.iloc[:, 0],
                conf_int.iloc[:, 1],
                alpha=0.20, color='#D32F2F', label='Intervalo de confianza 95%')

# Línea divisoria histórico / futuro
ax.axvline(x=ts.index.max(), color='gray',
           linestyle=':', linewidth=2, alpha=0.8, label='Último dato real')

# Etiquetas en cada punto proyectado
for fecha, valor in zip(fechas_futuras, pred_media):
    ax.annotate(f'₡{valor:,.0f}',
                xy=(fecha, valor),
                xytext=(0, 14),
                textcoords='offset points',
                ha='center', fontsize=9,
                color='#B71C1C', fontweight='bold')

ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
plt.xticks(rotation=45, ha='right')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'₡{x:,.0f}'))
ax.set_title(f'Proyección ARIMA({p_opt},{d_opt},{q_opt}): Próximos 5 Meses\n'
             f'Fuente: BCCR | Intervalo de confianza al 95%',
             fontsize=13, fontweight='bold')
ax.set_xlabel('Mes')
ax.set_ylabel('₡ por USD')
ax.legend(loc='upper left')
ax.set_ylim(bottom=ts_reciente.min() * 0.97)
plt.tight_layout()
plt.savefig('arima_proyeccion_futura.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica guardada: 'arima_proyeccion_futura.png'")

# --- Gráfica 3: ACF y PACF (diagnóstico del modelo) ---
# ACF  = Autocorrelation Function:  mide correlación con rezagos anteriores
# PACF = Partial ACF:               mide correlación directa con cada rezago
fig, axes = plt.subplots(1, 2, figsize=(14, 4))
plot_acf(ts['promedio'], lags=24, ax=axes[0],
         title='Función de Autocorrelación (ACF)')
plot_pacf(ts['promedio'], lags=24, ax=axes[1],
          title='Función de Autocorrelación Parcial (PACF)')
plt.suptitle('Diagnóstico de la Serie Temporal', fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('arima_acf_pacf.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Gráfica guardada: 'arima_acf_pacf.png'")

# Explotación de resultados

print("\n" + "=" * 60)
print("SECCIÓN L: EXPORTACIÓN DE RESULTADOS")
print("=" * 60)

# --- Guardar proyección en CSV ---
df_proyeccion_arima.to_csv('arima_proyeccion_5meses.csv', index=False, encoding='utf-8-sig')
print("💾 Proyección exportada: 'arima_proyeccion_5meses.csv'")

# --- Guardar comparación real vs predicho en CSV ---
df_comparacion.to_csv('arima_evaluacion_prueba.csv', index=False, encoding='utf-8-sig')
print("💾 Evaluación exportada: 'arima_evaluacion_prueba.csv'")

# Comparación de modelos y resumen final

print("\n" + "=" * 60)
print("SECCIÓN M: COMPARACIÓN FINAL DE MODELOS")
print("=" * 60)

# Calcular R² del ARIMA sobre el conjunto de prueba
ss_res  = np.sum((ts_test.values - pred_test.values) ** 2)
ss_tot  = np.sum((ts_test.values - ts_test.mean()) ** 2)
r2_arima = 1 - (ss_res / ss_tot)

print(f"""
  ╔══════════════════════════════════════════════════════════╗
  ║          COMPARACIÓN DE TODOS LOS MODELOS               ║
  ╠══════════════════════╦═══════════════╦══════════════════╣
  ║ Modelo               ║ R²            ║ Tipo             ║
  ╠══════════════════════╬═══════════════╬══════════════════╣
  ║ Lineal               ║ {r2_lineal:.4f}        ║ Regresión        ║
  ║ Polinomial Grado 2   ║ {r2_poly2:.4f}        ║ Regresión        ║
  ║ Polinomial Grado 3   ║ {r2_poly3:.4f}        ║ Regresión        ║
  ║ ARIMA({p_opt},{d_opt},{q_opt})          ║ {r2_arima:.4f}        ║ Series de tiempo ║
  ╚══════════════════════╩═══════════════╩══════════════════╝

  Métricas adicionales ARIMA (sobre conjunto de prueba):
    MAE  = ₡{mae:,.2f}
    RMSE = ₡{rmse:,.2f}
    MAPE = {mape:.2f}%

   Ventaja de ARIMA sobre regresión:
     Los modelos lineales/polinomiales ajustan una curva global
     que ignora la estructura temporal de los datos.
     ARIMA captura patrones de autocorrelación (cómo el valor
     de hoy depende de los valores pasados), lo que lo hace
     más adecuado para series de tiempo financieras.
""")


# =============================================================================
# RESUMEN EJECUTIVO FINAL
# =============================================================================

print("=" * 60)
print("RESUMEN EJECUTIVO – MODELO ARIMA")
print("=" * 60)
print(f"""
  Modelo ajustado:    ARIMA({p_opt}, {d_opt}, {q_opt})
  Serie analizada:    Tipo de cambio USD/CRC (2018–2025)
  Observaciones:      {n_total} meses
  División:           {n_train} entrenamiento / {n_test} prueba

  ─── Calidad del modelo ─────────────────────────────
  MAE   = ₡{mae:>10,.2f}  (error promedio absoluto)
  RMSE  = ₡{rmse:>10,.2f}  (penaliza errores grandes)
  MAPE  =  {mape:>9.2f}%  (error porcentual promedio)
  R²    =  {r2_arima:>9.4f}   (varianza explicada en prueba)

  ─── Proyección próximos 5 meses ────────────────────""")

for _, fila in df_proyeccion_arima.iterrows():
    print(f"  {fila['Mes']:<18} ₡{fila['Predicción ARIMA']:>10,.2f}  "
          f"[₡{fila['Límite Inferior 95%']:,.0f} – ₡{fila['Límite Superior 95%']:,.0f}]")

print(f"""
  ─── Archivos generados ─────────────────────────────
   arima_serie_original.png
   arima_diferenciacion.png       (si aplica)
   arima_evaluacion_prueba.png
   arima_proyeccion_futura.png
   arima_acf_pacf.png
   arima_proyeccion_5meses.csv
   arima_evaluacion_prueba.csv

    Nota: Las proyecciones son estimaciones estadísticas
      basadas en patrones históricos. No constituyen
      asesoría financiera ni predicciones garantizadas.
""")